# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-22 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('picUrl', models.CharField(max_length=500)),
                ('remark', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=2)),
                ('views', models.IntegerField()),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NoteCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('noteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Note')),
            ],
        ),
        migrations.CreateModel(
            name='NoteComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('author_reply', models.CharField(max_length=500, null=True)),
                ('author_replyTime', models.DateTimeField(auto_now=True, null=True)),
                ('noteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Note')),
            ],
        ),
        migrations.CreateModel(
            name='TBicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=2)),
                ('discover_type', models.CharField(max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=500)),
                ('picUrl', models.CharField(max_length=500)),
                ('createTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
                ('verify', models.CharField(max_length=2)),
                ('lanague', models.CharField(max_length=2)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('contactemail', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('pic', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('createTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='tbicture',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo'),
        ),
        migrations.AddField(
            model_name='notecomment',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo'),
        ),
        migrations.AddField(
            model_name='notecollection',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo'),
        ),
        migrations.AddField(
            model_name='note',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo'),
        ),
    ]
